Changed the order around!

diff --git a/kurzit b/kurzit
--- a/kurzit
+++ b/kurzit
@@ -13,6 +13,15 @@ ScriptName=$(basename $0)
 
 # Set the $kurzit_home variable
 if [ -z $kurzit_home ]; then
+    echo -n "Cannot find the kurzit_home variable..."
+    echo -n "Please type in the path:"
+    read kurzit_home
+    export kurzit_home
+        if ! [ -d $kurzit_home ]; then
+            echo Cannot find the kurzit_home variable, exiting script
+            exit 1
+        fi
+else
     # Check if $HOME/.kurzit exists, then use it for kurzit_home
     KURZIT_DIRS=(".kurzit" "kurzit")
     for DIR in $KURZIT_DIRS; do
@@ -23,15 +32,6 @@ if [ -z $kurzit_home ]; then
             fi
         fi
     done
-else
-    echo -n "Cannot find the kurzit_home variable..."
-    echo -n "Please type in the path:"
-    read kurzit_home
-    export kurzit_home
-        if ! [ -d $kurzit_home ]; then
-            echo Cannot find the kurzit_home variable, exiting script
-            exit 1
-        fi
 fi
 
 # Import Functions
