More testing!!!

diff --git a/kurzit b/kurzit
--- a/kurzit
+++ b/kurzit
@@ -10,48 +10,46 @@ BashVer=$(bash --version | head -n 1 | awk '{ print $4 }')
 Kern=$(uname -s)
 KernVer=$(uname -r)
 ScriptName=$(basename $0)
-TEST=$(pwd)
-echo $TEST
-
-function Set_KurzitHome () {
-    # 1st Check for empty variable
-    if [ -z $kurzit_home ]; then
-        # Check if $HOME/.kurzit exists, then use it for kurzit_home
-        if [ -d $HOME/.kurzit/ ]; then
-            if [ -e $HOME/.kurzit/kurzit ]; then
-                export kurzit_home=$HOME/.kurzit
-            fi
-        fi
-
-         # Check if $HOME/kurzit exists, then use it for kurzit_home
-        if [ -d $HOME/kurzit/ ]; then
-            if [ -e $HOME/kurzit/kurzit ]; then
-                export kurzit_home=$HOME/kurzit
-            fi
-        fi
-    fi
-
-    # 2nd Check for empty variable
-    if [ -z $kurzit_home ]; then
-        echo -n "Cannot find the kurzit_home variable..."
-        echo -n "Please type in the path:"
-        read kurzit_home
-        export kurzit_home
-            if ! [ -d $kurzit_home ]; then
-                echo Cannot find the kurzit_home variable, exiting script
-                exit 1
-            fi
-    fi
-}
-
-function Link_Kurzitrc () {
-    if [ ! -e ~/.kurzitrc ]; then
-        ln -s $kurzit_home/kurzitrc ~/.kurzitrc
-    fi
-}
 
 # Set the $kurzit_home variable
-Set_KurzitHome
+# 1st Check for empty variable
+if [ -z $kurzit_home ]; then
+    # Check if $HOME/.kurzit exists, then use it for kurzit_home
+    KURZIT_DIRS=(".kurzit" "kurzit")
+    for DIR in $KURZIT_DIRS
+    do
+        if [ -d $HOME/$DIR/ ]; then
+            if [ -e $HOME/$DIR/kurzit ]; then
+                echo "$HOME/$DIR"
+                export kurzit_home=$HOME/$DIR
+            fi
+        fi
+    done
+    #if [ -d $HOME/.kurzit/ ]; then
+    #    if [ -e $HOME/.kurzit/kurzit ]; then
+    #        export kurzit_home=$HOME/.kurzit
+    #    fi
+    #fi
+
+     # Check if $HOME/kurzit exists, then use it for kurzit_home
+    #if [ -d $HOME/kurzit/ ]; then
+    #    if [ -e $HOME/kurzit/kurzit ]; then
+    #        export kurzit_home=$HOME/kurzit
+    #    fi
+    #fi
+fi
+
+# 2nd Check for empty variable
+if [ -z $kurzit_home ]; then
+    echo -n "Cannot find the kurzit_home variable..."
+    echo -n "Please type in the path:"
+    read kurzit_home
+    export kurzit_home
+        if ! [ -d $kurzit_home ]; then
+            echo Cannot find the kurzit_home variable, exiting script
+            exit 1
+        fi
+fi
 
 # Import Functions
 for fn in $(find $kurzit_home/functions/ -type f ); do
@@ -60,8 +58,6 @@ done
 
 # Call Functions
 Get_Distro
-
-#Link_Kurzitrc
 
 # Searching for .bashrc, and exit if not found!
 if [ ! -e ~/.bashrc ]; then
